### ISSUE TITLE
cache items not contain `.git` dir

### ISSUE THREAD

**Issue by wuhuizuo** [j3t/jenkins-pipeline-cache-plugin#12]
I want using the plugin to cache git checkout speed, but I found it not store `.git`.

restore from cache object: 
<img width="503" alt="截屏2022-08-03 02 37 25" src="https://user-images.githubusercontent.com/2574558/182449024-2f7c92a1-3309-4af2-b209-27acd0bd847f.png">

**Comment by j3t** [comment]
Thanks for bringing this up. 

It seems that FilePath, which is used to create the tar archive, has default excludes (see https://ant.apache.org/manual/dirtasks.html#defaultexcludes) and .git is one of them. I'm not sure why, maybe because of sensitive data. We could disable the default excludes if the filter is set (e.g. **/*). I will create a PR and then we will see.

**Comment by j3t** [comment]
I'm still not sure about the final solution. Maybe it makes more sense to have `includes` and `excludes` as separate parameters and if `excludes` are not defined then the default excludes are used instead.

Any concerns/opinions?

**Comment by j3t** [comment]
@wuhuizuo It should be working now if you define a filter like `**/*`. BTW, what is your opinion about having `includes` and `excludes` as separate parameters?

**Comment by wuhuizuo** [comment]
> 

I like it. glob may be high level, special file can exclude by `excludes` options. I think `includes` may be conflict with `filter`.

I suggest filter support array to contain more glob patterns.
